# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CatFast' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SnapKit'

  # Pods for CatFast

  target 'CatFastTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CatFastUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
